import { Product } from "@/types/Payment";
export const data: Product[] = [
  {
    id: "m5gr84i9",
    quantity: 316,
    company: "bmw",
    index: "1",
    productCode: "Box Tissue ",
  },
  {
    id: "3u1reuv4",
    quantity: 242,
    index: "2",
    productCode: "Royal-Tissue-Box",
    company: "wurth",
  },
  {
    id: "derv1ws0",
    quantity: 837,
    index: "3",
    productCode: "_tissueboxAA",
    company: "bmw",
  },
  {
    id: "5kma53ae",
    quantity: 874,
    index: "4",
    productCode: "silicon",
    company: "wurth",
  },
  {
    id: "bhqecj4p",
    quantity: 721,
    index: "5",
    productCode: "A57980001",
    company: "Audi",
  },
  {
    id: "12",
    quantity: 7281,
    index: "6",
    company: "Fordlm",
    productCode: "carmelsla@hotmail.com",
  },
  {
    id: "43",
    quantity: 72111,
    index: "7",
    company: "Fordbr",
    productCode: "carmellakl,lm@hotmail.com",
  },
  {
    id: "saf",
    quantity: 72781,
    index: "8",
    company: "Fordhjk",
    productCode: "carmella@hoikltmail.com",
  },
  {
    id: "eafaa",
    quantity: 7621,
    index: "9",
    company: "Ford",
    productCode: "carmella@hotmaail.com",
  },
  {
    id: "fghjkl",
    quantity: 72661,
    index: "10",
    company: "Ford1",
    productCode: "carmella@hotmail.comsd",
  },
  {
    id: "qsxc",
    quantity: 721666,
    index: "11",
    company: "Ford2",
    productCode: "carmella@hotmail.coms",
  },
  {
    id: "ww",
    quantity: 72167,
    index: "12",
    company: "Ford4",
    productCode: "carmella@hotmail.com",
  },
  {
    id: "wwbhnm",
    quantity: 724321,
    index: "13",
    company: "X7",
    productCode: "Sillion",
  },
];
