import { Payment } from "@/types/Payment";
export const data: Payment[] = [
  {
    id: "m5gr84i9",
    amount: 316,
    company: "bmw",
    status: "1",
    email: "Box Tissue ",
  },
  {
    id: "3u1reuv4",
    amount: 242,
    status: "2",
    email: "Royal Tissue box",
    company: "wurth",
  },
  {
    id: "derv1ws0",
    amount: 837,
    status: "3",
    email: "_tissueboxAA",
    company: "bmw",
  },
  {
    id: "5kma53ae",
    amount: 874,
    status: "4",
    email: "silicon",
    company: "wurth",
  },
  {
    id: "bhqecj4p",
    amount: 721,
    status: "5",
    email: "A57980001",
    company: "Audi",
  },
  {
    id: "12",
    amount: 721,
    status: "6",
    company: "Ford",
    email: "carmella@hotmail.com",
  },
  {
    id: "43",
    amount: 721,
    status: "7",
    company: "Ford",
    email: "carmella@hotmail.com",
  },
  {
    id: "saf",
    amount: 721,
    status: "8",
    company: "Ford",
    email: "carmella@hotmail.com",
  },
  {
    id: "eafaa",
    amount: 721,
    status: "9",
    company: "Ford",
    email: "carmella@hotmail.com",
  },
  {
    id: "fghjkl",
    amount: 721,
    status: "10",
    company: "Ford",
    email: "carmella@hotmail.com",
  },
  {
    id: "qsxc",
    amount: 721,
    status: "failed",
    company: "Ford",
    email: "carmella@hotmail.com",
  },
  {
    id: "ww",
    amount: 721,
    status: "failed",
    company: "Ford",
    email: "carmella@hotmail.com",
  },
];
